<a href="https://colab.research.google.com/github/suneelkanthala/LearnDataScience/blob/master/U1W2_03_Numpy_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Advanced Certification in AIML
## A Program by IIIT-H and TalentSprint

## Objective :

At the end of this experiment, you will be able to :

* Use Numpy Library

## Setup Steps

In [ ]:
#@title Please enter your registration id to start: { run: "auto", display-mode: "form" }
Id = "2100030" #@param {type:"string"}


In [ ]:
#@title Please enter your password (normally your phone number) to continue: { run: "auto", display-mode: "form" }
password = "7674933144" #@param {type:"string"}


In [ ]:
#@title Run this cell to complete the setup for this Notebook
from IPython import get_ipython

ipython = get_ipython()
  
notebook= "U1W2_03_Numpy_Exercise" #name of the notebook
Answer = "Ungraded"
def setup():
#  ipython.magic("sx pip3 install torch")
    from IPython.display import HTML, display
    display(HTML('<script src="https://dashboard.talentsprint.com/aiml/record_ip.html?traineeId={0}&recordId={1}"></script>'.format(getId(),submission_id)))
    print("Setup completed successfully")
    return

def submit_notebook():
    
    ipython.magic("notebook -e "+ notebook + ".ipynb")
    
    import requests, json, base64, datetime

    url = "https://dashboard.talentsprint.com/xp/app/save_notebook_attempts"
    if not submission_id:
      data = {"id" : getId(), "notebook" : notebook, "mobile" : getPassword()}
      r = requests.post(url, data = data)
      r = json.loads(r.text)

      if r["status"] == "Success":
          return r["record_id"]
      elif "err" in r:        
        print(r["err"])
        return None        
      else:
        print ("Something is wrong, the notebook will not be submitted for grading")
        return None

    elif getAnswer() and getComplexity() and getAdditional() and getConcepts():
      f = open(notebook + ".ipynb", "rb")
      file_hash = base64.b64encode(f.read())

      data = {"complexity" : Complexity, "additional" :Additional, 
              "concepts" : Concepts, "record_id" : submission_id, 
              "answer" : Answer, "id" : Id, "file_hash" : file_hash,
              "notebook" : notebook}

      r = requests.post(url, data = data)
      r = json.loads(r.text)
      print("Your submission is successful.")
      print("Ref Id:", submission_id)
      print("Date of submission: ", r["date"])
      print("Time of submission: ", r["time"])
      print("View your submissions: https://iiith-aiml.talentsprint.com/notebook_submissions")
     # print("For any queries/discrepancies, please connect with mentors through the chat icon in LMS dashboard.")
      return submission_id
    else: submission_id
    

def getAdditional():
  try:
    if not Additional: 
      raise NameError
    else:
      return Additional  
  except NameError:
    print ("Please answer Additional Question")
    return None

def getComplexity():
  try:
    if not Complexity:
      raise NameError
    else:
      return Complexity
  except NameError:
    print ("Please answer Complexity Question")
    return None
  
def getConcepts():
  try:
    if not Concepts:
      raise NameError
    else:
      return Concepts
  except NameError:
    print ("Please answer Concepts Question")
    return None

def getAnswer():
  try:
    if not Answer:
      raise NameError 
    else: 
      return Answer
  except NameError:
    print ("Please answer Question")
    return None

def getId():
  try: 
    return Id if Id else None
  except NameError:
    return None

def getPassword():
  try:
    return password if password else None
  except NameError:
    return None

submission_id = None
### Setup 
if getPassword() and getId():
  submission_id = submit_notebook()
  if submission_id:
    setup()
    
else:
  print ("Please complete Id and Password cells before running setup")


Setup completed successfully


### 1. Import the numpy package under the name np

hint: import … as

In [ ]:
# YOUR CODE HERE
import numpy as np

### 2. Print the numpy version and the configuration

hint: np.__version__, np.show_config

In [ ]:
# YOUR CODE HERE
print(np.version)
print(np.show_config)

<module 'numpy.version' from '/usr/local/lib/python3.6/dist-packages/numpy/version.py'>
<function show at 0x7f36a0b561e0>


### 3. Create a null vector of size 10

hint: np.zeros

In [ ]:
# YOUR CODE HERE
zv = np.zeros(10)
print(zv)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


### 4. Create a null vector of size 10 but the fifth value which is 1

hint: array[4]

In [ ]:
# YOUR CODE HERE
v = np.zeros(10)
v[4] = 1
print(v)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


### 5. Create a vector with values ranging from 10 to 49

hint: arange

In [ ]:
# YOUR CODE HERE
v1 = np.arange(10,50)
print(v1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


### 6. Reverse a vector (first element becomes last)

hint: array[::-1]

In [ ]:
# YOUR CODE HERE
print(v1[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


### 7. Find indices of non-zero elements from [1,2,0,0,4,0]

hint: np.nonzero

In [ ]:
# YOUR CODE HERE
a = np.array([1,2,0,0,4,0])
print(np.nonzero(a))

(array([0, 1, 4]),)


### 8. Create a 3x3 identity matrix

hint: np.eye

In [ ]:
# YOUR CODE HERE
i = np.eye(3,3)
print(i)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### 9. Create a 3x3x3 array with random values

hint: np.random.random

In [ ]:
# YOUR CODE HERE
random = np.random.random((3,3,3))
print(random)


[[[0.77434554 0.32826524 0.78236665]
  [0.21406338 0.28822293 0.23946165]
  [0.07586395 0.8703562  0.83628124]]

 [[0.57265112 0.07776163 0.51690264]
  [0.81426149 0.12644275 0.80835966]
  [0.98803365 0.46374277 0.98161798]]

 [[0.10232978 0.71521224 0.10569878]
  [0.29939839 0.61016985 0.02235068]
  [0.48451091 0.49326644 0.94555915]]]


### 10. Create a 10x10 array with random values and find the minimum and maximum values

hint: min, max

In [ ]:
# YOUR CODE HERE
r1 = np.random.random((10,10))
print(np.min(r1))
print(np.max(r1))

0.004890774776773021
0.9867330392978128


### 11. Create a 5x5 matrix with values 1,2,3,4,5 just below the diagonal

hint: np.diag

In [ ]:
# YOUR CODE HERE
x = np.diag([1, 2, 3, 4, 5])
print(x)
np.tril([[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]], -1)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 2, 0, 0, 0],
       [1, 2, 3, 0, 0],
       [1, 2, 3, 4, 0]])

### 12. Matrix multiplication for 1-D array. 

To multiply the matrix a and b,
hint: np.dot

In [ ]:
import numpy as np

a = np.array([9, 5, 7, 4])
b = np.array([9, 5, 4, 3])

# YOUR CODE HERE
print(np.dot(a,b))
print(np.multiply(a,b))

146
[81 25 28 12]


## 13. Matrix multiplication for 2-D array.

To multiply the matrix a and b, 
hint: np.dot

In [ ]:
a = np.array([[1, 0],
             [0, 1]])

b = np.array([[4, 1],
              [2, 2]])


# YOUR CODE HERE
np.dot(a,b)

array([[4, 1],
       [2, 2]])

### 14. Transpose the given array [[ 1, 2, 3],[ 4, 5, 6],[ 7, 8, 9],[10, 11, 12]]
Hint :: np.transpose()

In [ ]:
# YOUR CODE HERE
a = np.array([[ 1, 2, 3],[ 4, 5, 6],[ 7, 8, 9],[10, 11, 12]])
np.transpose(a)

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

###15. Inverse the given array [[3,4],[5,6]]
Hint:: np.linalg.inv()

In [ ]:
# YOUR CODE HERE
a = np.array([[3,4],[5,6]])
np.linalg.inv(a)

array([[-3. ,  2. ],
       [ 2.5, -1.5]])

###16. Concatenate two numpy arrays by columnwise  by specifying axis 1
Hint::np.concatenate()

In [ ]:
c =np.array([[1,2],[3,4]])
d =np.array([[5,6],[7,8]])

# YOUR CODE HERE
np.concatenate((c,d), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

###17. For Given a Multidimensional array print second and third column


In [ ]:
a = np.array([[2, 4, 6, 8, 10], 
              [3, 6, 9, 12, 15], 
              [4, 8, 12, 16, 20]]) 

# YOUR CODE HERE
print(a[:,1:3])

[[ 4  6]
 [ 6  9]
 [ 8 12]]


###18. For Given Multidimensional array:
#### 1.Calculate mean row wise by specifying axis = 0 and column wise by specifying axis =1
#### 2. What is the average value of array

In [ ]:
import numpy as np 
# 2D array  
array = np.array([[2, 4, 6, 8, 10], 
              [3, 6, 9, 12, 15], 
              [4, 8, 12, 16, 20]]) 


#YOUR CODE HERE
print("mean of arr, axis = 0 : ", np.mean(array, axis = 0))
print("mean of arr, axis = 1 : ", np.mean(array, axis = 1))
np.average(array)

mean of arr, axis = 0 :  [ 3.  6.  9. 12. 15.]
mean of arr, axis = 1 :  [ 6.  9. 12.]


9.0

###19. Create an array of all the even numbers from 30 to 70.

In [ ]:
#YOUR CODE HERE
array=np.arange(30,71,2)
print(array)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


### 20. For the given array, get the slice of the first row and print them.

In [ ]:
import numpy as np

In [ ]:
a3 = np.array([[[10, 11, 12], [13, 14, 15], [16, 17, 18]],
               [[20, 21, 22], [23, 24, 25], [26, 27, 28]],
               [[30, 31, 32], [33, 34, 35], [36, 37, 38]]])


#YOUR CODE HERE
#print(a3)
print(a3[0])

[[10 11 12]
 [13 14 15]
 [16 17 18]]
